name: Build, publish Docker image & Deploy

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SSH_URL: ubuntu@ec2-18-118-70-119.us-east-2.compute.amazonaws.com
  APP_DIR: ~/shamir-videocreator

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        #setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - name: Run
        run: ssh -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no $SSH_URL 'echo "${{ secrets.PAT }}" | docker login ghcr.io -u SimonWT --password-stdin; cd ${{env.APP_DIR}}; ls; docker-compose pull frontend; docker-compose stop -t 1 frontend; docker-compose up -d frontend; docker image prune -a --force'

